version: '3'
    
services:

  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - mongo

  accounts:
    image: boeboe/digibank-accounts
    container_name: accounts
    env_file:
      - ./microservices/accounts/env.list
    ports:
      - "3400:3400"
    depends_on:
      - mongo

  authentication:
    image: boeboe/digibank-authentication
    container_name: authentication
    env_file:
      - ./microservices/authentication/env.list
    ports:
      - "3200:3200"
    depends_on:
      - mongo

  bills:
    image: boeboe/digibank-bills
    container_name: bills
    env_file:
      - ./microservices/bills/env.list
    ports:
      - "3800:3800"
    depends_on:
      - mongo

  portal:
    image: boeboe/digibank-portal
    container_name: portal
    env_file:
      - ./microservices/portal/env.list
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - accounts
      - authentication
      - bills
      - support
      - transactions

  support:
    image: boeboe/digibank-support
    container_name: support
    env_file:
      - ./microservices/support/env.list
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  transactions:
    image: boeboe/digibank-transactions
    container_name: transactions
    env_file:
      - ./microservices/transactions/env.list
    ports:
      - "3600:3600"
    depends_on:
      - mongo

  userbase:
    image: boeboe/digibank-userbase
    container_name: userbase
    env_file:
      - ./microservices/userbase/env.list
    ports:
      - "4200:4200"
    depends_on:
      - mongo
      - accounts
      - authentication
      - bills
      - transactions
